### ISSUE TITLE
Error: Cannot find module 'eslint-config-defaults/configurations/eslint'

### ISSUE THREAD

**Issue by falconmick** [coryhouse/react-flux-starter-kit#9] opened 2016-10-28 04:01 UTC
I made a clean download of the repo, ran the following:

npm install
gulp

and I got this:

```
C:\dev\tmp\react-flux-starter-kit\node_modules\gulp-eslint\node_modules\eslint\lib\config.js:129
                    throw e;
                    ^

Error: Cannot find module 'eslint-config-defaults/configurations/eslint'
Referenced from: C:\Users\xxx\.eslintrc
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at loadConfig (C:\dev\tmp\react-flux-starter-kit\node_modules\gulp-eslint\node_modules\eslint\lib\config.js:96:48)
    at C:\dev\tmp\react-flux-starter-kit\node_modules\gulp-eslint\node_modules\eslint\lib\config.js:123:46
    at Array.reduceRight (native)
    at loadConfig (C:\dev\tmp\react-flux-starter-kit\node_modules\gulp-eslint\node_modules\eslint\lib\config.js:111:36)
    at getPersonalConfig (C:\dev\tmp\react-flux-starter-kit\node_modules\gulp-eslint\node_modules\eslint\lib\config.js:194:18)
    at getLocalConfig (C:\dev\tmp\react-flux-starter-kit\node_modules\gulp-eslint\node_modules\eslint\lib\config.js:238:55)
```

looks like as I have eslint already installed that it is trying to use my newer version of eslint and it's funky config.

Is there a way to tell it to use the local over global?

**Comment by coryhouse** [comment] 2016-10-28 12:17
Thanks for the ticket! Can you share details about your environment? 
Node version
npm version
OS
Where are you running this? On the OS command line or via an editor?

**Comment by benjaminrlawrence** [comment] 2016-11-03 15:12
I'm having the same issue.  I'm on Windows 10, running in the CMD.exe command line. Node v4.6.0 and npm v2.15.9

**Comment by benjaminrlawrence** [comment] 2016-11-03 15:17
Fixed error when I installed npm modules eslint-config-defaults and then eslint-plugin-react (latest versions, which were 9.0.0 and 6.5.0, respectively). Now everything runs, but I get a linting error of "cannot find module 'babel-eslint'". I'll install that and report back.

**Comment by benjaminrlawrence** [comment] 2016-11-03 15:20
installing babel-eslint broke everything, I'll just run this with the error getting thrown within eslint.

**Comment by azizalibasic** [comment] 2016-11-09 22:41
@benjaminrlawrence I am getting the same error, did you get this solved? Making it difficult to do the plural sight course.

@coryhouse :
Node version: 7.1.0
npm version: 3.10.9
OS: WIndows 10
Where are you running this? : Git Bash
On the OS command line or via an editor? : Command Line

**Comment by benjaminrlawrence** [comment] 2016-11-09 22:45
@Kizer2 I was unable to solve this issue. What I did to continue the course was just do away with the linting task. All of the other tasks seem to be working, and you just don't get any linting, which is really okay. It's just a nice-to-have.

**Comment by coryhouse** [comment] 2016-11-10 21:29
Can one of you share your project on Github so I can try to reproduce?

**Comment by Havret** [comment] 2016-11-10 21:34
Here you are! It would would be great if you fix it. 

https://github.com/Havret/react-flux-starter-kit-master

**Comment by coryhouse** [comment] 2016-11-10 21:35
@Havret That repo is empty.

**Comment by Havret** [comment] 2016-11-10 21:38
@coryhouse It should be there now. Should I include node_modules dir as well? 

PS. Simple workaround is to comment out this troublesome gulp linting task.

**Comment by coryhouse** [comment] 2016-11-11 01:51
I have tried on both Mac and Windows and am unable to reproduce using @Havret repo or this course starter kit. One suggestion: delete the node_modules directory and re-run npm install. 

If that doesn't help, you can try deleting the node_module directory again and also deleting npm-shrinkwrap.json, then running npm install again.

**Comment by coryhouse** [comment] 2016-11-11 14:08
Please try adding this line to your .eslintrc and let me know if this resolves: https://github.com/coryhouse/react-slingshot/blob/master/.eslintrc#L2

**Comment by coryhouse** [comment] 2016-11-11 14:10
One final thing that is likely the root cause for you all:

Remove the .eslintrc file from your user's directory. I suspect you have a .eslintrc file in your user's directory that is conflicting with the course .eslintrc.

**Comment by Havret** [comment] 2016-11-11 15:00
Yes, it helped. Cheers!

**Comment by coryhouse** [comment] 2016-11-11 16:09
Excellent! Which change resolved the issue for you @Havret ?

**Comment by Havret** [comment] 2016-11-11 16:14
@coryhouse The second one. 

For the record, .eslintrc is coming back to to my user's directory once in a while (I presume after every single npm install?), breaking the whole thing again and again, so **remember to keep deleting it, if linting crashes**.

**Comment by benjaminrlawrence** [comment] 2016-11-11 18:43
I just did the same fix as @Havret. It works for me too.

**Comment by coryhouse** [comment] 2016-11-11 20:43
Great to hear! Closing since we've found the fix.

**Closed as completed by coryhouse** 2016-11-11 20:43 UTC

**Comment by maninderp** [comment] 2016-11-18 11:56
@coryhouse I also faced the same issue. Probably you should edit the PluralSight course to add a tip to delete the .eslintrc file from the users directory.
